In [36]:
import pandas as pd
import warnings
warnings.simplefilter('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,f1_score,precision_score,accuracy_score
from sklearn.metrics import roc_curve,auc
import matplotlib.pyplot as plt

micro=pd.read_csv('microsoft_20000.csv')
micro.drop(columns=['MachineIdentifier'],axis=1,inplace=True)
for col in micro.columns:
    if micro[col].isnull().sum() > 10000:
        micro.drop(col,axis=1,inplace=True)

y=pd.DataFrame()
y["output"]=micro["HasDetections"]
micro.drop("HasDetections",axis=1,inplace=True)

cat_list=[]
con_list=[]

for col in micro.columns:
    if micro[col].dtype == 'int64' or micro[col].dtype == 'float64':
        con_list.append(col)
    else:
        cat_list.append(col)

for col in micro[cat_list].columns:
    micro[col].fillna(value=micro[col].mode()[0],inplace=True)
    
for col in micro[con_list].columns:
    micro[col].fillna(value=micro[col].median(),inplace=True)

from statsmodels.stats.outliers_influence import variance_inflation_factor


vif = [[con_list[i],variance_inflation_factor(micro[con_list].values, i)] for i in range(micro[con_list].shape[1])]

drop_col=[]
for i in vif:
    if i[1] > 20:
        drop_col.append(i[0])
        
print(drop_col)

micro.drop(drop_col,axis=1,inplace=True)
    
X_train,X_test,y_train,y_test=train_test_split(micro,y,test_size=0.25,random_state=30)


le=LabelEncoder()
for col in cat_list:
    le.fit(X_train[col])
    X_test[col] = X_test[col].map(lambda s: '<unknown>' if s not in le.classes_ else s)
    le.classes_ = np.append(le.classes_, '<unknown>')
    X_train[col] = le.transform(X_train[col])
    X_test[col] = le.transform(X_test[col])
    

MScaling=MinMaxScaler()
for col in micro.columns:
    X_train[col]=MScaling.fit_transform(np.array(X_train[col]).reshape(-1,1))
    X_test[col]=MScaling.transform(np.array(X_test[col]).reshape(-1,1))

"""SScaling=StandardScaler()
for col in micro_dtypes['int or float']:
    X_train[col]=SScaling.fit_transform(np.array(X_train[col]).reshape(-1,1))
    X_test[col]=SScaling.transform(np.array(X_test[col]).reshape(-1,1))"""

#LogisticRegression model 

log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)
log_reg.predict(X_test)


print(f'confussion matrix =\n {confusion_matrix(y_test,log_reg.predict(X_test))}')

print(f'f1_score = {f1_score(y_test,log_reg.predict(X_test))}')

y_pre_pro=log_reg.predict_proba(X_test)[::,1]

fpr,tpr,threshold=roc_curve(y_test,y_pre_pro)
auc_score=auc(fpr,tpr)
auc_score

['RtpStateBitfield', 'AVProductStatesIdentifier', 'AVProductsEnabled', 'HasTpm', 'OrganizationIdentifier', 'OsBuild', 'IsProtected', 'IeVerIdentifier', 'Firewall', 'UacLuaenable', 'Census_ProcessorManufacturerIdentifier', 'Census_ProcessorModelIdentifier', 'Census_InternalPrimaryDisplayResolutionHorizontal', 'Census_InternalPrimaryDisplayResolutionVertical', 'Census_OSBuildNumber', 'Census_OSInstallLanguageIdentifier', 'Census_OSUILocaleIdentifier']
confussion matrix =
 [[1580  893]
 [1032 1495]]
f1_score = 0.6083418107833164


0.6632552820961037

In [37]:
#decision model

from sklearn.tree import DecisionTreeClassifier

Decision_class=DecisionTreeClassifier(max_depth=8,min_samples_split= 8,min_samples_leaf = 8,max_leaf_nodes= 5,criterion='gini')
Decision_class.fit(X_train,y_train)
Decision_class.predict(X_test)



print(f'confussion matrix =\n {confusion_matrix(y_test,Decision_class.predict(X_test))}')


print(f'Decision_class.score= {Decision_class.score(X_train,y_train)}')


print(f'f1_score = {f1_score(y_test,Decision_class.predict(X_test))}')

y_decesion_pro=pd.DataFrame(Decision_class.predict_proba(X_test)[::1])

fpr,tpr,threshold=roc_curve(y_test,y_decesion_pro[1])
auc_score_decesion=auc(fpr,tpr)
auc_score_decesion

confussion matrix =
 [[1221 1252]
 [ 706 1821]]
Decision_class.score= 0.6099073271551437
f1_score = 0.6503571428571429


0.6436793187557396

In [7]:
from sklearn.model_selection import RandomizedSearchCV

#parameters tuning for DecisionTreeClassifier

Param_dict_RSC = {
'max_depth':[4,5,6,7,8,9,10],
'min_samples_split':[2,3,4,5,6,7,8,9,10],
'min_samples_leaf':[2,3,4,5,6,7,8,9,10],
'max_leaf_nodes':[4,5,6,7,8,9,10],
"criterion": ["gini", "entropy"]}

rcv_DecisionTree = RandomizedSearchCV(Decision_class,Param_dict_RSC,cv=5,n_iter=15)
rcv_DecisionTree.fit(X_train,y_train)
rcv_DecisionTree.best_params_

{'min_samples_split': 8,
 'min_samples_leaf': 8,
 'max_leaf_nodes': 8,
 'max_depth': 5,
 'criterion': 'gini'}

In [38]:
from sklearn.ensemble import RandomForestClassifier

RandomForest=RandomForestClassifier(n_estimators=70,min_samples_split=8,min_samples_leaf=5,max_leaf_nodes=8,max_features=3,max_depth=5)

RandomForest.fit(X_train,y_train)
RandomForest.predict(X_test)


print(f'confussion matrix =\n {confusion_matrix(y_test,RandomForest.predict(X_test))}')
print(f'RandomForest.score= {RandomForest.score(X_train,y_train)}')
print(f'f1_score = {f1_score(y_test,RandomForest.predict(X_test))}')
print(f'precision_score = {precision_score(y_test,RandomForest.predict(X_test))}')


confussion matrix =
 [[1492  981]
 [ 915 1612]]
RandomForest.score= 0.6232415494366291
f1_score = 0.6296874999999998
precision_score = 0.6216737369841882


In [26]:
#parameters tuning for RandomForestClassifier

parameters_Random={'n_estimators':[70,80,100],
                   'max_depth':[5,6,7,8], 
                   "min_samples_split":[2,3,4,5,6,7,8,9,10], 
                   'min_samples_leaf':[2,3,4,5,6,7,8,9,10], 
                   'max_features':['auto','log2',3,4,5], 
                   'max_leaf_nodes':[4,5,6,7,8,9,10]}

rcv_RandomForestClassifier=RandomizedSearchCV(RandomForest,parameters_Random,cv=5,n_iter=15)
rcv_RandomForestClassifier.fit(X_train,y_train)
rcv_RandomForestClassifier.best_params_

{'n_estimators': 80,
 'min_samples_split': 6,
 'min_samples_leaf': 7,
 'max_leaf_nodes': 8,
 'max_features': 4,
 'max_depth': 8}

In [40]:
from sklearn.ensemble import GradientBoostingClassifier

GBC=GradientBoostingClassifier(learning_rate=0.1,min_samples_split=0.1,
                                max_depth=6,min_samples_leaf=0.1,max_features=10)

GBC.fit(X_train,y_train)
GBC.predict(X_test)
y_pred=GBC.predict_proba(X_test)[::,1]

print(f'confussion matrix =\n {confusion_matrix(y_test,GBC.predict(X_test))}')
print(f'RandomForest.score= {GBC.score(X_train,y_train)}')
print(f'f1_score = {f1_score(y_test,GBC.predict(X_test))}')
print(f'precision_score = {precision_score(y_test,GBC.predict(X_test))}')

from sklearn.metrics import roc_curve, auc

false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc


confussion matrix =
 [[1615  858]
 [1038 1489]]
RandomForest.score= 0.6408427228481899
f1_score = 0.6109971276159213
precision_score = 0.6344269279931828


0.673612650179517